#!/bin/bash
set -e

# === NoCornyTracer signing setup (one-time, per maintainer machine) ===
#
# Prepares everything scripts/release.sh needs to produce a notarized Developer ID
# build, WITHOUT ever putting a secret in a file, argv, or shell history:
#
#   1. Confirms a "Developer ID Application" certificate is in the keychain
#      (and tells you clearly if you accidentally made an "Apple Development" one).
#   2. Stores your notary credentials in the Keychain via `xcrun notarytool
#      store-credentials` — it prompts you for the app-specific password directly;
#      this script never sees or handles it.
#   3. Writes scripts/release.env (gitignored, non-secrets only) so releases just work.
#   4. Verifies the credential profile actually authenticates.
#
# Re-running is safe. Nothing here needs sudo.

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE_NAME="${NOTARY_PROFILE:-NoCornyTracerNotary}"
RELEASE_ENV="$PROJECT_DIR/scripts/release.env"

echo "🔐 NoCornyTracer signing setup"
echo "==============================="
echo ""

# --- Step 1: find the Developer ID Application certificate -----------------------
echo "1️⃣  Checking for a 'Developer ID Application' certificate..."
DEVID_LINES="$(security find-identity -v -p codesigning | grep 'Developer ID Application' || true)"
DEVID_COUNT="$(printf '%s' "$DEVID_LINES" | grep -c 'Developer ID Application' || true)"

if [ "${DEVID_COUNT:-0}" -eq 0 ]; then
    echo "❌ No 'Developer ID Application' certificate found in the keychain."
    echo ""
    if security find-identity -v -p codesigning | grep -q 'Apple Development'; then
        echo "   You DO have an 'Apple Development' certificate — but that is the WRONG type."
        echo "   'Apple Development' is for running builds on your own devices; the notary"
        echo "   service rejects it. You need a 'Developer ID Application' certificate for"
        echo "   distributing outside the App Store."
        echo ""
    fi
    echo "   Create the right one:"
    echo "     Xcode ▸ Settings ▸ Accounts ▸ (your team) ▸ Manage Certificates ▸ + ▸"
    echo "       Developer ID Application"
    echo "   (or via the portal: developer.apple.com/account/resources/certificates)"
    echo ""
    echo "   Then re-run this script."
    exit 1
elif [ "$DEVID_COUNT" -gt 1 ]; then
    echo "⚠️  Multiple 'Developer ID Application' certificates found:"
    printf '%s\n' "$DEVID_LINES"
    echo "   That's fine — release.sh will ask you to pick one via SIGN_IDENTITY if it"
    echo "   can't auto-detect. Using the first one below just to read the Team ID."
fi

IDENTITY_LINE="$(printf '%s\n' "$DEVID_LINES" | head -1)"
IDENTITY_NAME="$(printf '%s' "$IDENTITY_LINE" | sed -n 's/.*"\(.*\)".*/\1/p')"
TEAM_ID="$(printf '%s' "$IDENTITY_LINE" | sed -n 's/.*(\([A-Z0-9]\{10\}\))".*/\1/p')"
echo "✅ Found: $IDENTITY_NAME"
echo "   Team ID: ${TEAM_ID:-<could not parse>}"
echo ""

if [ -z "$TEAM_ID" ]; then
    echo "❌ Could not parse the Team ID from the certificate name. Aborting."
    exit 1
fi

# Warn if the private key is missing (a cert with no key can't sign — a common
# "imported the .cer but not the key" mistake).
if ! security find-identity -v -p codesigning | grep -q "$IDENTITY_NAME"; then
    echo "❌ The certificate has no usable private key in this keychain. Re-create it"
    echo "   (the private key is generated on YOUR Mac when you make the CSR)."
    exit 1
fi

# --- Step 2: Apple ID + notarytool credentials ----------------------------------
DEFAULT_APPLE_ID="$(git -C "$PROJECT_DIR" config user.email 2>/dev/null || true)"
echo "2️⃣  Storing notary credentials in the Keychain (profile: $PROFILE_NAME)"
echo "    You'll need an app-specific password: https://account.apple.com ▸"
echo "    Sign-In and Security ▸ App-Specific Passwords ▸ +  (label it 'notarytool')."
echo "    notarytool will prompt you for it — I never see or store it."
echo ""
read -r -p "   Apple ID email${DEFAULT_APPLE_ID:+ [$DEFAULT_APPLE_ID]}: " APPLE_ID
APPLE_ID="${APPLE_ID:-$DEFAULT_APPLE_ID}"
if [ -z "$APPLE_ID" ]; then
    echo "❌ An Apple ID email is required."
    exit 1
fi
echo ""

# Deliberately OMIT --password so notarytool shows its own secure prompt: the secret
# never enters this script, the process argv, or ~/.zsh_history.
xcrun notarytool store-credentials "$PROFILE_NAME" \
    --apple-id "$APPLE_ID" \
    --team-id "$TEAM_ID"

echo ""

# --- Step 3: write the gitignored release.env -----------------------------------
echo "3️⃣  Writing scripts/release.env (gitignored, non-secrets only)..."
cat > "$RELEASE_ENV" <<EOF
# Generated by scripts/setup_signing.sh — DO NOT COMMIT (gitignored).
# Non-secrets only. The app-specific password lives in the macOS Keychain under the
# notarytool profile below; it is NEVER stored here.
#
# release.sh sources this file so 'bash scripts/release.sh' works with no env vars.
NOTARY_PROFILE="$PROFILE_NAME"
# SIGN_IDENTITY is auto-detected from the keychain (the sole Developer ID Application
# cert). Uncomment and set to a SHA-1 hash only if you have more than one such cert:
# SIGN_IDENTITY="$(printf '%s' "$IDENTITY_LINE" | awk '{print $2}')"
EOF
echo "✅ Wrote $RELEASE_ENV"
echo ""

# --- Step 4: verify the profile authenticates -----------------------------------
echo "4️⃣  Verifying the notary profile authenticates..."
if xcrun notarytool history --keychain-profile "$PROFILE_NAME" >/dev/null 2>&1; then
    echo "✅ Notary profile '$PROFILE_NAME' works."
else
    echo "❌ Could not authenticate with profile '$PROFILE_NAME'."
    echo "   Double-check the Apple ID, the app-specific password, and Team ID $TEAM_ID,"
    echo "   then re-run this script."
    exit 1
fi

echo ""
echo "==============================================================="
echo "✅ Signing setup complete."
echo ""
echo "   ⚠️  BACK UP YOUR PRIVATE KEY before your first release:"
echo "      Keychain Access ▸ My Certificates ▸ '$IDENTITY_NAME' ▸ (expand, confirm a"
echo "      private key is nested) ▸ File ▸ Export Items… ▸ .p12 ▸ set a strong password."
echo "      Apple cannot re-issue this key. Losing it forces a signing-authority change"
echo "      that breaks Sparkle auto-updates for every existing user."
echo ""
echo "   Next: build a notarized DMG with"
echo "      NOTARIZE=1 bash scripts/build_dmg.sh"
echo "   or cut a full release with"
echo "      bash scripts/release.sh --publish"
echo "==============================================================="
